[build]
  command = "npm run build"
  publish = "build/"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-inline-source"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
